# 100 Python Interview Questions

### Q01 — What is the difference between a list and a tuple?

Lists are mutable — you can change them after creation. Tuples are immutable — once created, that's it. Tuples are slightly faster and are used when the data shouldn't change: coordinates, RGB values, function return pairs.

In [7]:
# List (Mutable)
my_list = [1, 2, 3]
my_list[0] = 99
print("List:", my_list)

List: [99, 2, 3]

In [8]:
# Tuple (Immutable)
my_tuple = (1, 2, 3)
# my_tuple[0] = 99  # This would raise a TypeError
print("Tuple:", my_tuple)

Tuple: (1, 2, 3)

Immutable
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 3
      1 # Tuple (Immutable)
      2 my_tuple = (1, 2, 3)
----> 3 my_tuple[0] = 99  # This would raise a TypeError
      4 print("Tuple:", my_tuple)

TypeError: 'tuple' object does not support item assignment
```

### Q02 — What does `*args` and `**kwargs` do?

`*args` collects extra positional arguments into a tuple. `**kwargs` collects extra keyword arguments into a dict. You use them when you don't know in advance how many arguments a function will receive.

In [ ]:
def show(*args, **kwargs):
    print(args)  # tuple
    print(kwargs)  # dict


show(1, 2, name="Alice")  # (1, 2), {'name': 'Alice'}

(1, 2)
{'name': 'Alice'}

### Q03 — What is the difference between == and is?

== checks if two values are equal. is checks if they're the same object in memory. Two variables can be == without being is. Small integers (-5 to 256) and short strings are cached so is might return True — but never rely on that.

In [10]:
a = [1, 2, 3]
b = [1, 2, 3]
c = a

print("a == b:", a == b)  # True (values are equal)
print("a is b:", a is b)  # False (different objects in memory)
print("a is c:", a is c)  # True (same object in memory)

a == b: True
a is b: False
a is c: True

### Q04 — What are mutable and immutable types in Python?

Mutable: list, dict, set, bytearray. Immutable: int, float, str, tuple, bool, frozenset. Immutable objects can be used as dict keys. Mutable objects passed to a function can be modified inside it — that surprises people.

In [ ]:
# Mutable: modifying a list inside a function affects the original
def add_item(lst):
    lst.append(4)


my_list = [1, 2, 3]
add_item(my_list)
print("Mutable (List):", my_list)


# Immutable: modifying an integer creates a new object
def increment(n):
    n += 1


my_int = 10
increment(my_int)
print("Immutable (Int):", my_int)  # Still 10

Mutable (List): [1, 2, 3, 4]
Immutable (Int): 10

### Q05 — What is a list comprehension and when do you use it?

A compact way to build a list: [expr for item in iterable if condition]. Use it when the logic is simple enough to read in one line. When you need nested loops or 3+ conditions, use a regular loop.

In [12]:
numbers = [1, 2, 3, 4, 5, 6]

# Regular loop
evens = []
for n in numbers:
    if n % 2 == 0:
        evens.append(n)

# List comprehension (more compact)
evens_comp = [n for n in numbers if n % 2 == 0]

print(evens)
print(evens_comp)

[2, 4, 6]
[2, 4, 6]

### Q06 — What is the difference between append() and extend()?

append() adds one item to the end. extend() adds elements from an iterable. lst.append([1,2]) makes the list one longer. lst.extend([1,2]) adds both.

In [13]:
lst1 = [1, 2, 3]
lst1.append([4, 5])
print("append:", lst1)  # Adds the list as a single element

lst2 = [1, 2, 3]
lst2.extend([4, 5])
print("extend:", lst2)  # Adds each element from the iterable

append: [1, 2, 3, [4, 5]]
extend: [1, 2, 3, 4, 5]

### Q07 — How does Python handle memory management?

Python uses reference counting plus a garbage collector. When an object's reference count drops to zero, it is deallocated. The gc module handles cyclic references.

In [14]:
import sys

# Reference counting example
my_var = "Hello, Python!"
# getrefcount returns 1 more than expected because the argument passed to getrefcount also creates a reference
print("Reference count:", sys.getrefcount(my_var))

Reference count: 3

### Q08 — What is a lambda function?

An anonymous function written in one line: lambda args: expr. The expression is always returned — no return needed. Use with map(), filter(). Never assign a lambda to a variable if you can avoid it.

In [ ]:
names = ["Alice", "Bob", "Charlie", "Dave"]

# Sort names by their length using a lambda function
sorted_names = sorted(names, key=lambda name: len(name))
print(sorted_names)

['Bob', 'Dave', 'Alice', 'Charlie']

### Q09 — What is the difference between deepcopy and copy?

copy.copy() is a shallow copy — it copies the outer container but nested objects are still shared. copy.deepcopy() copies everything recursively. Use deepcopy when shallow copy means modifying a nested list affects the original.

In [ ]:
import copy

original = [[1, 2], [3, 4]]

shallow = copy.copy(original)
deep = copy.deepcopy(original)

original[0][0] = 99

print("Original:", original)
print("Shallow:", shallow)  # Affected by change in original
print("Deep:", deep)  # Unaffected

Original: [[99, 2], [3, 4]]
Shallow: [[99, 2], [3, 4]]
Deep: [[1, 2], [3, 4]]

### Q10 — What does __name__ == '__main__' do?

Python sets __name__ to '__main__' only when the file is executed directly. If imported, __name__ is the module name. This lets you write code that runs when executed directly but not when imported.

In [ ]:
def main():
    print("This script is running directly.")


if __name__ == "__main__":
    main()

This script is running directly.

### Q11 — What is the GIL and why does it matter?

The Global Interpreter Lock is a mutex that prevents multiple threads from executing Python bytecode simultaneously. This means threads don't give you true CPU parallelism for CPU-bound tasks. Use multiprocessing. For I/O-bound work (network, disk), threads are fine because they release the GIL while waiting.

In [ ]:
import threading
import time


def cpu_bound_task():
    for _ in range(10**7):
        pass


# GIL prevents these two threads from running in true parallel on multiple cores
start = time.time()
t1 = threading.Thread(target=cpu_bound_task)
t2 = threading.Thread(target=cpu_bound_task)
t1.start()
t2.start()
t1.join()
t2.join()
print(f"Time taken: {time.time() - start:.2f} seconds")

Time taken: 0.59 seconds

### Q12 — What is slicing and how does it work?

lst[start:stop:step] — start is inclusive, stop is exclusive. lst[::-1] reverses. lst[::2] gives every other element. Negative indices count from the end. Slicing never raises IndexError — if you go out of bounds it just returns what's there.

In [ ]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print("lst[2:7]:", lst[2:7])  # From index 2 up to (but not including) 7
print("lst[::2]:", lst[::2])  # Every second element
print("lst[::-1]:", lst[::-1])  # Reversed
print("lst[100:200]:", lst[100:200])  # Out of bounds doesn't raise error

lst[2:7]: [2, 3, 4, 5, 6]
lst[::2]: [0, 2, 4, 6, 8]
lst[::-1]: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
lst[100:200]: []

### Q13 — What are Python's built-in data types?

int, float, complex, bool, str, bytes, list, tuple, set, frozenset, dict, NoneType. Everything in Python is an object, including functions and classes.

In [ ]:
# Example of various data types
print(type(10))  # int
print(type(3.14))  # float
print(type(1 + 2j))  # complex
print(type(True))  # bool
print(type("Hello"))  # str
print(type([1, 2]))  # list
print(type((1, 2)))  # tuple
print(type({1, 2}))  # set
print(type({"a": 1}))  # dict

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>

### Q14 — What is the difference between range() and xrange()?

In Python 3, xrange() doesn't exist — range() is already lazy (returns a range object, not a list). In Python 2, range() returned a list and xrange() was the lazy version. If you're asked this, clarify which Python version and note that Python 2 is end-of-life.

In [21]:
# In Python 3, range() returns a lazy range object, not a full list in memory.
r = range(1000000)
print("Type of range:", type(r))

# You can still iterate over it efficiently
for i in range(3):
    print(i)

Type of range: <class 'range'>
0
1
2

### Q15 — How do you reverse a list in Python?

Three ways: list.reverse() in place, lst[::-1] returns a new reversed list, list(reversed(lst)) uses an iterator. The interviewer usually wants you to know all three and explain the difference.

In [22]:
lst = [1, 2, 3, 4, 5]

# 1. In-place reverse
lst.reverse()
print("In-place:", lst)

# 2. Slicing (returns new list)
new_lst = lst[::-1]
print("Slicing:", new_lst)

# 3. Built-in reversed() (returns iterator)
rev_iter = list(reversed(lst))
print("reversed():", rev_iter)

In-place: [5, 4, 3, 2, 1]
Slicing: [1, 2, 3, 4, 5]
reversed(): [1, 2, 3, 4, 5]

### Q16 — What is the difference between remove(), pop(), and del?

remove(val) removes the first occurrence of a value. pop(i) removes by index and returns the element. del lst[i] removes by index, returns nothing. pop() with no argument removes the last element.

In [ ]:
lst = ["a", "b", "c", "d", "e"]

lst.remove("c")  # Removes by value
print("After remove('c'):", lst)

popped = lst.pop(1)  # Removes by index and returns it
print("After pop(1):", lst, "| Popped:", popped)

del lst[0]  # Removes by index, returns nothing
print("After del lst[0]:", lst)

After remove('c'): ['a', 'b', 'd', 'e']
After pop(1): ['a', 'd', 'e'] | Popped: b
After del lst[0]: ['d', 'e']

### Q17 — What is string interning?

Python automatically reuses the same string object for short strings and identifiers. So a = 'hello'; b = 'hello'; a is b is True. Not guaranteed for all strings — longer strings or strings with spaces may not be interned. Use == for string comparison, never is.

In [24]:
a = "hello"
b = "hello"
print("a is b:", a is b)  # True, string is interned

c = "hello world!"
d = "hello world!"
print("c is d:", c is d)  # May be False depending on environment/version

a is b: True
c is d: False

### Q18 — What are Python's comparison operators and how does chaining work?

Python allows chaining: 1 < x < 10 is valid and means 1 < x and x < 10. Most languages don't support this. It only evaluates x once.

In [25]:
x = 5

# Chained comparison
print("1 < x < 10:", 1 < x < 10)  # Same as 1 < x and x < 10
print("10 > x >= 5:", 10 > x >= 5)

1 < x < 10: True
10 > x >= 5: True

### Q19 — What is the difference between str() and repr()?

str() is for human-readable output. repr() is for developer-readable output — it should ideally return something that could recreate the object. repr() is what the console shows.

In [26]:
import datetime

now = datetime.datetime.now()

# Human readable
print("str():", str(now))

# Developer readable (often valid Python code to recreate the object)
print("repr():", repr(now))

str(): 2026-07-08 15:09:07.252940
repr(): datetime.datetime(2026, 7, 8, 15, 9, 7, 252940)

### Q20 — How do you swap two variables in Python?

a, b = b, a — Python evaluates the right side first as a tuple, then unpacks. No temp variable needed. This is the expected answer in interviews.

In [27]:
a = 10
b = 20

print(f"Before: a={a}, b={b}")

# Tuple packing and unpacking
a, b = b, a

print(f"After: a={a}, b={b}")

Before: a=10, b=20
After: a=20, b=10

## 🟣 Functions & Scope — Q21 to Q35

> 🎯 Scope and closures trip up most candidates. These questions separate people who understand Python from those who just use it.

### Q21 — What is the LEGB rule?

Python looks up names in this order: Local -> Enclosing -> Global -> Built-in. If a name isn't found at one level, it goes up. This is Python's scoping rule — understanding it explains most "variable not defined" errors.

In [ ]:
x = "Global"


def outer():
    x = "Enclosing"

    def inner():
        x = "Local"
        print(x)  # Finds Local first

    inner()


outer()

Local

### Q22 — What is a closure?

A function that remembers the variables from its enclosing scope even after the outer function has finished. The inner function "closes over" those variables.

In [ ]:
def make_multiplier(n):
    def multiply(x):
        return x * n  # n is from enclosing scope

    return multiply


double = make_multiplier(2)
print(double(5))  # 10 — n=2 is remembered

10

### Q23 — What is the mutable default argument trap?

Default arguments are evaluated once when the function is defined, not each time it's called. If you use a mutable default like [] or {}, it persists between calls.

In [ ]:
# Wrong
def add(item, lst=[]):
    lst.append(item)


# Right
def add(item, lst=None):
    if lst is None:
        lst = []
    lst.append(item)
    return lst

### Q24 — What does global and nonlocal do?

global lets a function read AND write a global variable. Without it, assigning to a name inside a function creates a local variable. nonlocal does the same for enclosing (not global) scope — useful in closures.

In [ ]:
x = 10  # Global variable
y = 20


def outer():
    y = 30  # Enclosing variable

    def inner():
        global x
        nonlocal y
        x = 99
        y = 99

    inner()
    print("outer y:", y)


outer()
print("global x:", x)

outer y: 99
global x: 99

### Q25 — What is a decorator?

A function that wraps another function to extend or modify its behaviour without changing the original. The @ syntax is just shorthand: @my_decorator on top of def f(): is the same as f = my_decorator(f).

In [ ]:
def log(func):
    def wrapper(*args, **kwargs):
        print(f"Calling {func.__name__}")
        return func(*args, **kwargs)

    return wrapper


@log
def greet(name):
    return f"Hi {name}"

### Q26 — What is a generator and how is it different from a list?

A generator produces values one at a time using yield. It doesn't store the whole sequence in memory — values are computed on demand. x**2 for x in range(million) uses constant memory. [x**2 for x in range(million)] uses 8MB.

In [33]:
import sys

# List: computes all values and stores in memory
lst = [x**2 for x in range(10000)]
print("List size (bytes):", sys.getsizeof(lst))

# Generator: computes on demand
gen = (x**2 for x in range(10000))
print("Generator size (bytes):", sys.getsizeof(gen))

List size (bytes): 85176
Generator size (bytes): 208

### Q27 — What does yield do?

Pauses the function and returns a value to the caller. When the generator is called again, it resumes from where it left off. A function with yield is a generator function — calling it returns a generator object.

In [ ]:
def simple_generator():
    print("Generating 1")
    yield 1
    print("Generating 2")
    yield 2


gen = simple_generator()
print(next(gen))
print(next(gen))

Generating 1
1
Generating 2
2

### Q28 — What is functools.wraps and why use it?

When you wrap a function with a decorator, the wrapper replaces the original's __name__, __doc__, etc. functools.wraps(func) preserves those attributes so debugging tools and docs still show the original function's name.

In [ ]:
from functools import wraps


def my_decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        """Wrapper docstring"""
        return func(*args, **kwargs)

    return wrapper


@my_decorator
def example():
    """Example docstring"""
    pass


# Without @wraps, this would print "wrapper" and "Wrapper docstring"
print("Name:", example.__name__)
print("Doc:", example.__doc__)

Name: example
Doc: Example docstring

### Q29 — What is the difference between a function and a method?

A method is a function defined inside a class that receives self as its first argument. All methods are functions — not all functions are methods.

In [ ]:
class MyClass:
    def method(self):
        print("This is a method. I have self:", self)


def function():
    print("This is a standalone function.")


obj = MyClass()
obj.method()
function()

This is a method. I have self: <__main__.MyClass object at 0x0000029E5E430590>
This is a standalone function.

### Q30 — What does map() return in Python 3?

A map object — a lazy iterator, not a list. Wrap with list() to see results. This is a common interview gotcha: map(func, lst) doesn't immediately execute anything.

In [37]:
numbers = [1, 2, 3]

# map() returns a map object (an iterator)
mapped = map(lambda x: x * 2, numbers)

print("Map object:", mapped)
print("Evaluated list:", list(mapped))

Map object: <map object at 0x0000029E5E48C6C0>
Evaluated list: [2, 4, 6]

### Q31 — What is filter() and how is it different from a list comprehension?

filter(fn, lst) returns elements where fn(element) is True. Equivalent to [x for x in lst if fn(x)]. Both are fine — comprehensions are usually more readable. filter(None, lst) removes falsy values.

In [38]:
numbers = [1, 2, 3, 4, 5, 6]

# Using filter
evens_filter = list(filter(lambda x: x % 2 == 0, numbers))

# Using list comprehension
evens_comp = [x for x in numbers if x % 2 == 0]

print("filter:", evens_filter)
print("comprehension:", evens_comp)

filter: [2, 4, 6]
comprehension: [2, 4, 6]

### Q32 — What does sorted() return vs .sort()?

sorted() returns a new sorted list, leaving the original unchanged. .sort() sorts in place and returns None. Classic mistake: lst = lst.sort() gives you None.

In [39]:
lst1 = [3, 1, 4, 1, 5]
sorted_lst = sorted(lst1)
print("sorted() returns new list:", sorted_lst)
print("Original is unchanged:", lst1)

lst2 = [3, 1, 4, 1, 5]
result = lst2.sort()
print(".sort() modifies in-place:", lst2)
print("Returns:", result)  # None

sorted() returns new list: [1, 1, 3, 4, 5]
Original is unchanged: [3, 1, 4, 1, 5]
.sort() modifies in-place: [1, 1, 3, 4, 5]
Returns: None

### Q33 — What is partial application with functools.partial?

Creates a new function with some arguments pre-filled.

In [ ]:
from functools import partial


def power(base, exp):
    return base**exp


square = partial(power, exp=2)
print(square(5))  # 25

25

### Q34 — How does Python's zip() work?

Pairs elements from multiple iterables. Stops at the shortest. dict(zip(keys, vals)) is one of the most used patterns. zip(*matrix) transposes a 2D list.

In [ ]:
names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 35]

# Pair elements together
paired = list(zip(names, ages))
print("Zipped:", paired)

# Convert to dictionary
name_age_dict = dict(zip(names, ages))
print("Dict:", name_age_dict)

Zipped: [('Alice', 25), ('Bob', 30), ('Charlie', 35)]
Dict: {'Alice': 25, 'Bob': 30, 'Charlie': 35}

### Q35 — What is enumerate() and when do you use it?

Wraps an iterable and returns (index, value) pairs. Always use it instead of range(len(lst)) when you need both. enumerate(lst, start=1) starts counting from 1.

In [ ]:
colors = ["red", "green", "blue"]

# enumerate gives you both index and value
for index, color in enumerate(colors, start=1):
    print(f"{index}: {color}")

1: red
2: green
3: blue

## 🟤 Data Structures — Q36 to Q50

> 🎯 Dict internals, sets, and complexity questions appear in almost every technical screen.

### Q36 — How does a Python dictionary work internally?

Dicts use a hash table. Keys are hashed and the hash determines where the value is stored. Lookup is O(1) average case. Keys must be hashable (immutable). Since Python 3.7, dicts preserve insertion order.

In [ ]:
# Dictionaries preserve insertion order (Python 3.7+)
d = {}
d["b"] = 2
d["a"] = 1
d["c"] = 3

print("Dict:", d)
print("Keys:", list(d.keys()))  # Output follows insertion order: 'b', 'a', 'c'

Dict: {'b': 2, 'a': 1, 'c': 3}
Keys: ['b', 'a', 'c']

### Q37 — What makes an object hashable?

An object is hashable if it has a __hash__ method that returns the same value for its lifetime, and a __eq__ method. Immutable types are hashable. Mutable types (list, dict, set) are not — you can't use them as dict keys.

In [ ]:
class CustomHashable:
    def __init__(self, value):
        self.value = value

    def __hash__(self):
        return hash(self.value)

    def __eq__(self, other):
        return self.value == other.value


# We can use it as a dict key
obj = CustomHashable("secret")
d = {obj: "data"}
print("Found data:", d[CustomHashable("secret")])

Found data: data

### Q38 — What is a set and when do you use it?

An unordered collection of unique hashable elements. Membership testing is O(1). Use sets for: deduplication, membership checks, and set operations (union, intersection, difference).

In [45]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}

print("Union:", set_a | set_b)
print("Intersection:", set_a & set_b)
print("Difference:", set_a - set_b)

Union: {1, 2, 3, 4, 5}
Intersection: {3}
Difference: {1, 2}

### Q39 — What is the difference between a set and a frozenset?

A frozenset is an immutable set. It can be used as a dict key or as an element in another set. Regular sets cannot.

In [46]:
mutable_set = {1, 2, 3}
immutable_set = frozenset([1, 2, 3])

# mutable_set.add(4)  # Allowed
# immutable_set.add(4)  # Raises AttributeError

# Frozensets can be used as dict keys
d = {immutable_set: "valid"}
print(d)

{frozenset({1, 2, 3}): 'valid'}

### Q40 — What is a defaultdict?

From collections. Like a regular dict but returns a default value for missing keys instead of raising KeyError. defaultdict(list) returns [] for missing keys, defaultdict(int) returns 0.

In [ ]:
from collections import defaultdict

d = defaultdict(list)
d["key"].append(1)  # no KeyError

### Q41 — What is a Counter?

From collections. Counts hashable objects. Counter('aababc') gives {'a': 3, 'b': 2, 'c': 1}. most_common(n) returns top N. Useful for frequency analysis, anagram detection.

In [48]:
from collections import Counter

word = "abracadabra"
counts = Counter(word)

print("Character counts:", counts)
print("Top 2 most common:", counts.most_common(2))

Character counts: Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})
Top 2 most common: [('a', 5), ('b', 2)]

### Q42 — What is a deque?

From collections. Double-ended queue. Append and pop from both ends in O(1). Lists are O(n) for operations at the front. Use deque for queues, sliding windows, and BFS.

In [ ]:
from collections import deque

dq = deque([1, 2, 3])
dq.append(4)  # O(1)
dq.appendleft(0)  # O(1)

print("Deque:", dq)

dq.pop()  # O(1)
dq.popleft()  # O(1)
print("After pops:", dq)

Deque: deque([0, 1, 2, 3, 4])
After pops: deque([1, 2, 3])

### Q43 — What is the time complexity of common list operations?

| Operation | Complexity |
| --- | --- |
| append | O(1) amortized |
| insert at index | O(n) |
| pop (end) | O(1) |
| pop (index) | O(n) |
| in operator | O(n) |
| index lookup | O(1) |

In [50]:
import time

lst = list(range(100000))

# pop() from end is O(1) - fast
start = time.time()
lst.pop()
print("pop() time:", time.time() - start)

# pop(0) from beginning is O(n) - slow
start = time.time()
lst.pop(0)
print("pop(0) time:", time.time() - start)

pop() time: 0.00012731552124023438
pop(0) time: 0.00032782554626464844

### Q44 — What is the time complexity of dict and set operations?

Lookup, insert, delete: O(1) average, O(n) worst case (hash collision). In practice always treat as O(1). The in operator on a set is O(1) vs O(n) for a list — this matters at scale.

In [51]:
my_set = set(range(1000000))
my_list = list(range(1000000))

import time

# O(1) lookup
start = time.time()
_ = 999999 in my_set
print("Set lookup time:", time.time() - start)

# O(n) lookup
start = time.time()
_ = 999999 in my_list
print("List lookup time:", time.time() - start)

Set lookup time: 0.00015163421630859375
List lookup time: 0.020712614059448242

### Q45 — How do you merge two dicts?

Python 3.9+: merged = d1 | d2. Before 3.9: merged = {**d1, **d2}. Both create a new dict. d1.update(d2) modifies d1 in place. In case of duplicate keys, the second dict wins.

In [ ]:
d1 = {"a": 1, "b": 2}
d2 = {"b": 3, "c": 4}

# Python 3.9+ syntax
merged = d1 | d2
print("Merged:", merged)  # d2 wins the conflict for 'b'

Merged: {'a': 1, 'b': 3, 'c': 4}

### Q46 — What is dict comprehension?

{k: v for k, v in items} — builds a dict in one line. {v: k for k, v in d.items()} flips a dict. {k: v for k, v in d.items() if v > 0} filters.

In [53]:
squares = {x: x**2 for x in range(1, 6)}
print("Squares dict:", squares)

# Flip keys and values
flipped = {v: k for k, v in squares.items()}
print("Flipped dict:", flipped)

Squares dict: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
Flipped dict: {1: 1, 4: 2, 9: 3, 16: 4, 25: 5}

### Q47 — What is the difference between list() and []?

[] is a literal — faster. list() calls the constructor — can convert any iterable. list('abc') gives ['a', 'b', 'c']. For creating empty lists, always use [].

In [54]:
# list() creates a new list from an iterable
iterable_list = list("hello")
print(iterable_list)

# [] creates a list literal directly (faster for empty lists)
empty_list = []
print(empty_list)

['h', 'e', 'l', 'l', 'o']
[]

### Q48 — How do you sort a list of dicts by a key?

sorted(lst, key=lambda d: d['field']) — don't need to import anything. reverse=True for descending. key=lambda d: (d['a'], d['b']) for multi-field sort.

In [ ]:
data = [
    {"name": "Alice", "age": 30},
    {"name": "Bob", "age": 25},
    {"name": "Charlie", "age": 35},
]

# Sort by age
sorted_data = sorted(data, key=lambda d: d["age"])
for row in sorted_data:
    print(row)

{'name': 'Bob', 'age': 25}
{'name': 'Alice', 'age': 30}
{'name': 'Charlie', 'age': 35}

### Q49 — What is heapq used for?

Python's heap implementation — a min-heap. heapq.nlargest(n, lst) and heapq.nsmallest(n, lst) are faster than sorting the whole list when n is small. Used in Dijkstra's algorithm.

In [56]:
import heapq

numbers = [10, 4, 2, 8, 20, 15, 6]

# Get the 3 largest numbers efficiently
largest = heapq.nlargest(3, numbers)
print("Top 3 largest:", largest)

# Get the 3 smallest numbers efficiently
smallest = heapq.nsmallest(3, numbers)
print("Top 3 smallest:", smallest)

Top 3 largest: [20, 15, 10]
Top 3 smallest: [2, 4, 6]

### Q50 — What is bisect used for?

Binary search on sorted lists. bisect.bisect_left(lst, x) finds the insertion point. O(log n). Use when you need to search or insert into a sorted list efficiently.

In [57]:
import bisect

sorted_lst = [10, 20, 30, 40, 50]

# Find where to insert 25 to keep the list sorted
index = bisect.bisect_left(sorted_lst, 25)
print("Insert 25 at index:", index)

# Insert it
bisect.insort(sorted_lst, 25)
print("List after insert:", sorted_lst)

Insert 25 at index: 2
List after insert: [10, 20, 25, 30, 40, 50]

## 🟢 OOP — Q51 to Q65

> 🎯 OOP questions test depth. Interviewers want to see that you understand why these concepts exist, not just the syntax.

### Q51 — What are the four pillars of OOP?

Encapsulation (bundle data + methods, control access), Inheritance (child gets parent's attributes + can add/override), Polymorphism (same method name, different behaviour per class), Abstraction (hide complexity, expose interface).

In [ ]:
# Example showing Encapsulation and Inheritance
class Animal:
    def __init__(self, name):
        self._name = name  # Encapsulation (protected)

    def speak(self):
        pass  # Abstraction


class Dog(Animal):  # Inheritance
    def speak(self):
        return "Woof!"  # Polymorphism


d = Dog("Buddy")
print(f"{d._name} says {d.speak()}")

Buddy says Woof!

### Q52 — What is the difference between __str__ and __repr__?

__str__ is for humans — what print() shows. __repr__ is for developers — what the console shows, ideally something that could recreate the object. If only __repr__ is defined, Python uses it for both.

In [ ]:
class Person:
    def __init__(self, name):
        self.name = name

    def __str__(self):
        return f"Person: {self.name}"

    def __repr__(self):
        return f"Person(name='{self.name}')"


p = Person("Alice")
print(str(p))  # Human-readable
print(repr(p))  # Developer-readable

Person: Alice
Person(name='Alice')

### Q53 — What is super() and why is it needed?

super() calls the parent class's method. Always call super().__init__() in a child class — without it the parent's setup never runs, causing AttributeErrors. In multiple inheritance, super() follows the MRO.

In [ ]:
class Parent:
    def __init__(self):
        print("Parent init called")


class Child(Parent):
    def __init__(self):
        super().__init__()  # Calls Parent.__init__
        print("Child init called")


c = Child()

Parent init called
Child init called

### Q54 — What is the MRO (Method Resolution Order)?

The order Python searches for methods in a class hierarchy. Use ClassName.__mro__ or ClassName.mro() to inspect it. Python uses the C3 linearization algorithm. This matters most with multiple inheritance.

In [ ]:
class A:
    pass


class B(A):
    pass


class C(A):
    pass


class D(B, C):
    pass


# Shows Method Resolution Order
print("MRO for D:")
for cls in D.mro():
    print(" -", cls.__name__)

MRO for D:
 - D
 - B
 - C
 - A
 - object

### Q55 — What is the difference between class, static, and instance methods?

Instance methods receive self — access instance + class data. Class methods receive cls — access class data only, decorated with @classmethod. Static methods receive neither — utility functions, decorated with @staticmethod.

In [ ]:
class MathHelper:
    def __init__(self, value):
        self.value = value

    def instance_method(self):
        return self.value * 2

    @classmethod
    def class_method(cls):
        return "I have access to cls:", cls.__name__

    @staticmethod
    def static_method(x, y):
        return x + y


obj = MathHelper(10)
print(obj.instance_method())
print(MathHelper.class_method())
print(MathHelper.static_method(5, 5))

20
('I have access to cls:', 'MathHelper')
10

### Q56 — What is @property?

Makes a method look like an attribute. Lets you add validation or computation to attribute access without changing how callers use the class. Pair with @attr.setter for controlled writes.

In [ ]:
class Circle:
    def __init__(self, radius):
        self._radius = radius

    @property
    def radius(self):
        return self._radius

    @radius.setter
    def radius(self, value):
        if value < 0:
            raise ValueError("Radius cannot be negative")
        self._radius = value


c = Circle(5)
c.radius = 10  # Calls the setter
print("Radius:", c.radius)  # Calls the property getter

Radius: 10

### Q57 — What is the difference between _name, __name, and __name__?

_name — convention: protected, don't access outside class. __name — name-mangled by Python to _ClassName__name, harder to access accidentally. __name__ — dunder attribute, part of Python's protocol.

In [ ]:
class SecretData:
    def __init__(self):
        self._protected = "Please don't touch"
        self.__private = "Harder to touch"


obj = SecretData()
print(obj._protected)

# obj.__private will raise an error
# You must access it via name mangling:
print(obj._SecretData__private)

Please don't touch
Harder to touch

### Q58 — What is an abstract class?

A class that can't be instantiated directly. Forces subclasses to implement required methods. Use from abc import ABC, abstractmethod. If a subclass doesn't implement all abstract methods, instantiating it raises TypeError.

In [ ]:
from abc import ABC, abstractmethod


class Shape(ABC):
    @abstractmethod
    def area(self):
        pass


class Square(Shape):
    def __init__(self, side):
        self.side = side

    def area(self):
        return self.side**2


# s = Shape()  # Raises TypeError
sq = Square(4)
print("Square area:", sq.area())

Square area: 16

### Q59 — What is duck typing?

"If it walks like a duck and quacks like a duck, it's a duck." Python doesn't check types — it checks whether an object has the required method or attribute. This is why len() works on strings, lists, dicts, and custom objects as long as they implement __len__.

In [ ]:
class Duck:
    def quack(self):
        print("Quack!")


class Person:
    def quack(self):
        print("I'm pretending to be a duck!")


def make_it_quack(thing):
    thing.quack()  # Python doesn't care about the type, just the method


make_it_quack(Duck())
make_it_quack(Person())

Quack!
I'm pretending to be a duck!

### Q60 — What is a dataclass?

Decorator from dataclasses. Automatically generates __init__, __repr__, __eq__ based on field annotations. Less boilerplate for data-container classes. frozen=True makes it immutable.

In [ ]:
from dataclasses import dataclass


@dataclass
class Point:
    x: float
    y: float
    z: float = 0.0


p1 = Point(1.5, 2.5)
p2 = Point(1.5, 2.5)

print(p1)  # Automatically has a nice __repr__
print(p1 == p2)  # Automatically has __eq__ checking fields

Point(x=1.5, y=2.5, z=0.0)
True

### Q61 — What is __slots__?

Replaces the per-instance __dict__ with a fixed set of attributes. Reduces memory usage significantly for classes with many instances. Trade-off: you can't add arbitrary attributes at runtime.

In [ ]:
class NoSlots:
    def __init__(self):
        self.x = 1


class WithSlots:
    __slots__ = ["x"]

    def __init__(self):
        self.x = 1


obj1 = NoSlots()
obj1.y = 2  # Allowed

obj2 = WithSlots()
# obj2.y = 2  # Raises AttributeError - saves memory!

### Q62 — What is the difference between aggregation and composition?

Composition: the contained object can't exist without the container. Aggregation: it can. A Car composed of an Engine — destroy the car, the engine is destroyed. A Team aggregating Players — dissolve the team, players still exist.

In [ ]:
class Engine:
    pass


class Player:
    pass


class Car:
    def __init__(self):
        self.engine = Engine()  # Composition: Engine dies with Car


class Team:
    def __init__(self, players):
        self.players = players  # Aggregation: Players exist without Team

### Q63 — What is a context manager and how do you write one?

Implement __enter__ and __exit__ on a class, then use it with with. __enter__ sets up, __exit__ tears down (even if an exception occurs). Or use @contextmanager from contextlib with yield.

In [ ]:
class MyContext:
    def __enter__(self):
        print("Entering context")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print("Exiting context")
        if exc_type:
            print(f"Exception occurred: {exc_value}")
        return True  # Suppress exceptions


with MyContext() as ctx:
    print("Inside context")
    raise ValueError("Oops!")

Entering context
Inside context
Exiting context
Exception occurred: Oops!

### Q64 — What is multiple inheritance and what problem does it cause?

A class can inherit from multiple parents. The diamond problem: if two parents both inherit from the same grandparent, which version of the grandparent's method runs? Python resolves this with MRO. super() follows MRO so each class in the chain is called once.

In [ ]:
class Base:
    def do_stuff(self):
        print("Base")


class A(Base):
    def do_stuff(self):
        print("A")
        super().do_stuff()


class B(Base):
    def do_stuff(self):
        print("B")
        super().do_stuff()


class C(A, B):
    def do_stuff(self):
        print("C")
        super().do_stuff()


C().do_stuff()  # C -> A -> B -> Base

C
A
B
Base

### Q65 — What is the difference between isinstance() and type()?

isinstance(obj, ClassName) returns True for the class and any subclass. type(obj) == ClassName is strict — only True for that exact class. Always prefer isinstance() because it respects inheritance.

In [ ]:
class Animal:
    pass


class Dog(Animal):
    pass


d = Dog()

print("isinstance(d, Animal):", isinstance(d, Animal))  # True
print("type(d) == Animal:", type(d) == Animal)  # False

isinstance(d, Animal): True
type(d) == Animal: False

## 🔴 Error Handling & File I/O — Q66 to Q75

### Q66 — What is the structure of try/except/else/finally?

try — code that might fail. except — runs if exception occurs. else — runs if NO exception occurred. finally — always runs, exception or not. Use else for code that should only run on success — cleaner than putting it in try.

In [ ]:
def divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError:
        print("Cannot divide by zero!")
    else:
        print(f"Result is {result}")
    finally:
        print("Execution completed.")


divide(10, 2)
divide(10, 0)

Result is 5.0
Execution completed.
Cannot divide by zero!
Execution completed.

### Q67 — What is the difference between Exception and BaseException?

Exception is the base for most user-facing exceptions. BaseException also includes SystemExit, KeyboardInterrupt, GeneratorExit — things you usually don't want to catch. Always catch Exception, not BaseException, unless you specifically need those.

In [74]:
import sys

try:
    sys.exit(0)
except Exception:
    print("This won't catch sys.exit()")
except BaseException:
    print("This WILL catch sys.exit(), KeyboardInterrupt, etc.")

This WILL catch sys.exit(), KeyboardInterrupt, etc.

### Q68 — What happens if you use bare except:?

It catches everything including KeyboardInterrupt and SystemExit — your program can't be stopped with Ctrl+C. Always use except Exception: at minimum, or better, catch specific exceptions.

In [ ]:
try:
    x = 1 / 0
except:  # Avoid this! Catches EVERYTHING
    print("An error occurred.")

try:
    x = 1 / 0
except Exception as e:  # Better!
    print(f"Caught an Exception: {e}")

An error occurred.
Caught an Exception: division by zero

### Q69 — How do you raise a custom exception?

Subclass Exception. You can add __init__ to pass custom data. Use raise ... from err to chain exceptions and preserve the original traceback.

In [ ]:
class ValidationError(Exception):
    pass


raise ValidationError("Amount must be positive")

ValidationError: Amount must be positive

### Q70 — What is with open() and why use it?

Context manager for file operations. Automatically closes the file when the block exits — even if an exception occurs. Never use raw open() without with. with open('f.txt') as f: is the right pattern.

In [77]:
# Writing to a file using 'with' ensures it is properly closed
with open("example.txt", "w") as f:
    f.write("Hello, World!")

# Reading from it
with open("example.txt", "r") as f:
    content = f.read()
    print("File content:", content)

File content: Hello, World!

### Q71 — What is the difference between read(), readline(), and readlines()?

read() — entire file as one string. readline() — one line at a time. readlines() — all lines as a list. For large files, iterate the file object directly: for line in f: — memory efficient.

In [79]:
with open("example.txt", "w") as f:
    f.write("Line 1\n Line 2\n Line 3")

with open("example.txt", "r") as f:
    print("read():\n ", f.read())

with open("example.txt", "r") as f:
    print("readlines():", f.readlines())

read():
  Line 1
 Line 2
 Line 3
readlines(): ['Line 1\n', ' Line 2\n', ' Line 3']

### Q72 — What file modes are available in open()?

'r' read, 'w' write (overwrites), 'a' append, 'rb' / 'wb' binary, 'r+' read+write. Default is 'r'. 'w' creates the file if it doesn't exist and wipes it if it does.

In [ ]:
# 'w' overwrites, 'a' appends, 'r' reads
with open("test.txt", "w") as f:
    f.write("First line\n")

with open("test.txt", "a") as f:
    f.write("Second line appended\n")

with open("test.txt", "r") as f:
    print(f.read())

First line
Second line appended

### Q73 — How do you handle encoding issues when reading files?

Always specify encoding='utf-8' explicitly: open('f.txt', encoding='utf-8'). Without it, Python uses the system default which varies by OS. Use errors='ignore' or errors='replace' if the file has bad characters.

In [82]:
# Explicit encoding prevents OS-specific defaults from corrupting data
text = "Café"

with open("cafe.txt", "w", encoding="utf-8") as f:
    f.write(text)

with open("cafe.txt", "r", encoding="utf-8") as f:
    print(f.read())

Café

### Q74 — What is pathlib and why is it better than os.path?

pathlib.Path represents file paths as objects. Path('subdir') / 'file.txt' instead of os.path.join(). Methods like exists(), read_text(), write_text(), suffix, stem are all built in. Much cleaner than string-based path manipulation.

In [84]:
from pathlib import Path

# Create a Path object
p = Path("my_folder") / "subfolder" / "data.txt"

print("Path object:", p)
print("File suffix:", p.suffix)
print("Parent dir:", p.parent)

# Methods are convenient
# p.write_text("Data")
# print(p.exists())

Path object: my_folder\subfolder\data.txt
File suffix: .txt
Parent dir: my_folder\subfolder

### Q75 — What does assert do and when should you NOT use it?

assert condition, 'message' raises AssertionError if condition is False. Use for development-time checks and test assertions. Never use for input validation or business logic in production — assert statements are disabled when Python runs with the -O flag.

In [85]:
def process_age(age):
    assert age >= 0, "Age cannot be negative!"
    return age * 2


print(process_age(25))
# process_age(-5)  # Raises AssertionError

50

## ⚫ pandas & Data — Q76 to Q88

> 🎯 These come up in every data analyst/scientist role. Real questions about real daily use.

### Q76 — What is the difference between loc and iloc?

loc is label-based — inclusive on both ends. iloc is position-based — exclusive on the right (like Python slicing). df.loc[0:5] returns 6 rows. df.iloc[0:5] returns 5.

In [104]:
import pandas as pd

# Let's create a DataFrame with custom string indices
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]}, index=['row_a', 'row_b', 'row_c', 'row_d'])

print("--- Original DataFrame ---")
display(df)

# loc is label-based. It includes both the start and the end label!
print("\n --- Using loc['row_b':'row_c'] (inclusive) ---")
display(df.loc['row_b':'row_c'])

# iloc is integer-position based. It is exclusive of the end index, just like Python lists!
print("\n --- Using iloc[1:3] (exclusive of 3) ---")
display(df.iloc[1:3])

--- Original DataFrame ---

          Name  Age
row_a    Alice   25
row_b      Bob   30
row_c  Charlie   35
row_d    David   40

 --- Using loc['row_b':'row_c'] (inclusive) ---

          Name  Age
row_b      Bob   30
row_c  Charlie   35

 --- Using iloc[1:3] (exclusive of 3) ---

          Name  Age
row_b      Bob   30
row_c  Charlie   35

### Q77 — What does axis=0 vs axis=1 mean in pandas?

axis=0 operates down rows — gives one value per column. axis=1 operates across columns — gives one value per row. df.drop('col', axis=1) drops a column. df.sum(axis=0) sums each column.

In [103]:
import pandas as pd

# Imagine a gradebook for students
df = pd.DataFrame({'Math': [90, 80],'Science': [85, 95]}, index=['Alice', 'Bob'])

print("--- Original DataFrame ---")
display(df)

# axis=0 (or axis='index') moves vertically downwards across rows.
# It calculates the sum for each column.
print("\n --- Sum across axis=0 (Total per subject) ---")
display(df.sum(axis=0))

# axis=1 (or axis='columns') moves horizontally across columns.
# It calculates the sum for each row.
print("\n --- Sum across axis=1 (Total per student) ---")
display(df.sum(axis=1))

--- Original DataFrame ---

       Math  Science
Alice    90       85
Bob      80       95

 --- Sum across axis=0 (Total per subject) ---

Math       170
Science    180
dtype: int64

 --- Sum across axis=1 (Total per student) ---

Alice    175
Bob      175
dtype: int64

### Q78 — What is the difference between apply() and map() in pandas?

map() works on a Series, element by element. apply() works on Series or DataFrame — df.apply(fn, axis=1) applies row-wise. applymap() (now map() in newer pandas) applies element-wise on a DataFrame.

In [102]:
import pandas as pd

df = pd.DataFrame({
    'Price': [10.0, 20.0, 30.0],
    'Tax': [1.0, 2.0, 3.0]})

print("--- Original DataFrame ---")
display(df)

# map() is a Series method. It applies a function element-wise to a single column.
df['Price_Mapped'] = df['Price'].map(lambda x: f"${x:.2f}")
print("\n --- After map() on 'Price' column ---")
display(df)

# apply() can be used on a DataFrame to apply a function across rows or columns.
# Here we apply a function to each row (axis=1) to calculate the Total.
df['Total'] = df.apply(lambda row: row['Price'] + row['Tax'], axis=1)
print("\n --- After apply() across rows ---")
display(df)

--- Original DataFrame ---

   Price  Tax
0   10.0  1.0
1   20.0  2.0
2   30.0  3.0

 --- After map() on 'Price' column ---

   Price  Tax Price_Mapped
0   10.0  1.0       $10.00
1   20.0  2.0       $20.00
2   30.0  3.0       $30.00

 --- After apply() across rows ---

   Price  Tax Price_Mapped  Total
0   10.0  1.0       $10.00   11.0
1   20.0  2.0       $20.00   22.0
2   30.0  3.0       $30.00   33.0

### Q79 — How do you handle missing values in pandas?

df.isnull().sum() to count. dropna() to remove rows/columns. fillna(value) to replace — can use method='ffill' or method='bfill'. For numeric columns, fill with median: df['col'].fillna(df['col'].median()).

In [ ]:
import pandas as pd
import numpy as np

# Create a DataFrame with some missing values (NaN)
df = pd.DataFrame({
    'Product': ['Apple', 'Banana', 'Cherry', 'Date'],
    'Stock': [100, np.nan, 50, np.nan],
    'Price': [1.2, 0.5, np.nan, 2.0]})

print("--- Original DataFrame with missing values ---")
display(df)

# 1. Fill missing values with a specific number (e.g., 0)
print("\n--- Using fillna(0) ---")
display(df.fillna(0))

# 2. Drop any rows that contain missing values
print("\n--- Using dropna() ---")
display(df.dropna())

--- Original DataFrame with missing values ---

  Product  Stock  Price
0   Apple  100.0    1.2
1  Banana    NaN    0.5
2  Cherry   50.0    NaN
3    Date    NaN    2.0

--- Using fillna(0) ---

  Product  Stock  Price
0   Apple  100.0    1.2
1  Banana    0.0    0.5
2  Cherry   50.0    0.0
3    Date    0.0    2.0

--- Using dropna() ---

  Product  Stock  Price
0   Apple  100.0    1.2

### Q80 — What is groupby() and how does named aggregation work?

groupby() groups rows and applies aggregation. Named aggregation in agg() gives clean column names: df.groupby('region').agg(total=('revenue', 'sum'), avg=('revenue', 'mean')). No renaming step needed.

In [100]:
import pandas as pd

# Sales data for different regions and products
df = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South', 'East'],
    'Sales': [200, 150, 300, 100, 400],
    'Profit': [50, 20, 80, 10, 100]
    })

print("--- Original Data ---")
display(df)

# groupby() splits the data into groups based on 'Region'.
# We can then apply aggregate functions like sum() or mean() to each group.
print("\n --- Total Sales and Profit by Region ---")
grouped = df.groupby('Region').sum(numeric_only=True)
display(grouped)

# We can also do named aggregations for specific columns
print("\n --- Named Aggregation (Max Sales, Avg Profit) ---")
named_agg = df.groupby('Region').agg(
    Max_Sales=('Sales', 'max'),
    Avg_Profit=('Profit', 'mean'))

display(named_agg)

--- Original Data ---

  Region  Sales  Profit
0  North    200      50
1  North    150      20
2  South    300      80
3  South    100      10
4   East    400     100

 --- Total Sales and Profit by Region ---

        Sales  Profit
Region
East      400     100
North     350      70
South     400      90

 --- Named Aggregation (Max Sales, Avg Profit) ---

        Max_Sales  Avg_Profit
Region
East          400       100.0
North         200        35.0
South         300        45.0

### Q81 — What is the difference between merge() and concat()?

merge() is SQL-style JOIN — combines on a key column. concat() stacks DataFrames vertically (axis=0) or horizontally (axis=1). Always use ignore_index=True with concat to reset index.

In [99]:
import pandas as pd

# concat() is like stacking Lego blocks (either vertically or horizontally)
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})
print("--- concat() (Vertical Stacking) ---")
display(pd.concat([df1, df2], ignore_index=True))

# merge() is like a SQL JOIN, combining DataFrames based on a common key
employees = pd.DataFrame({'EmpID': [1, 2], 'Name': ['Alice', 'Bob']})
departments = pd.DataFrame({'EmpID': [2, 1], 'Dept': ['Engineering', 'HR']})
print("\n --- merge() (SQL-style JOIN on 'EmpID') ---")
display(pd.merge(employees, departments, on='EmpID'))

--- concat() (Vertical Stacking) ---

   A
0  1
1  2
2  3
3  4

 --- merge() (SQL-style JOIN on 'EmpID') ---

   EmpID   Name         Dept
0      1  Alice           HR
1      2    Bob  Engineering

### Q82 — What does pd.melt() do?

Converts wide format to long format. Turns column headers into a column of values. id_vars are the columns to keep as-is. value_vars are the columns to unpivot.

In [98]:
import pandas as pd

# Wide format: Columns represent variables (e.g., different months)
df_wide = pd.DataFrame({
    'Store': ['Store A', 'Store B'],
    'Jan_Sales': [100, 200],
    'Feb_Sales': [150, 250]})

print("--- Wide Format (Good for human reading) ---")
display(df_wide)

# pd.melt() unpivots the DataFrame from wide to long format.
# Long format is often required for machine learning or plotting libraries (like Seaborn).
df_long = pd.melt(
    df_wide, 
    id_vars=['Store'], 
    value_vars=['Jan_Sales', 'Feb_Sales'],
    var_name='Month', 
    value_name='Sales')

print("\n --- Long Format (Good for analysis/plotting) ---")
display(df_long)

--- Wide Format (Good for human reading) ---

     Store  Jan_Sales  Feb_Sales
0  Store A        100        150
1  Store B        200        250

 --- Long Format (Good for analysis/plotting) ---

     Store      Month  Sales
0  Store A  Jan_Sales    100
1  Store B  Jan_Sales    200
2  Store A  Feb_Sales    150
3  Store B  Feb_Sales    250

### Q83 — What is vectorisation in NumPy/pandas?

Applying an operation to the whole array at once instead of looping. arr * 2 multiplies every element — no Python loop. 10-100x faster than equivalent loops because operations are implemented in C. Always prefer vectorised operations over iterrows().

In [96]:
import numpy as np
import time

# Create a large array of numbers
arr = np.arange(5_000_000)

print("Squaring 5 million numbers...\n ")

# 1. The Slow Way (Python for-loop)
start = time.time()
loop_result = [x**2 for x in arr]
loop_time = time.time() - start

print(f"Loop time: {loop_time:.4f} seconds")

# 2. The Fast Way (Vectorisation)
# Vectorisation delegates the operation to optimized C code, avoiding Python's loop overhead.
start = time.time()
vector_result = arr**2
vector_time = time.time() - start

print(f"Vectorised time: {vector_time:.4f} seconds")
print(f"\n Vectorisation was {loop_time / vector_time:.1f}x faster!")

Squaring 5 million numbers...

Loop time: 0.8362 seconds
Vectorised time: 0.0147 seconds

 Vectorisation was 57.0x faster!

### Q84 — What is broadcasting in NumPy?

Applying operations between arrays of different shapes without loops. arr + 1 broadcasts scalar across every element. arr.mean(axis=0) subtracts column means from every row — the mean (shape M) broadcasts across N rows. The rule: dimensions are compatible if they're equal or one of them is 1.

In [97]:
import numpy as np
import pandas as pd

# Broadcasting allows arithmetic operations between arrays of different shapes.
# The smaller array is "broadcast" across the larger array.

matrix = np.array([[10, 20, 30], [40, 50, 60]])

row_vector = np.array([1, 2, 3])

print("--- Original Matrix (2x3) ---")
print(matrix)
print("\n --- Row Vector (1x3) ---")
print(row_vector)

# The row_vector is added to EVERY row of the matrix automatically!
print("\n --- Result of Matrix + Row Vector ---")
print(matrix + row_vector)

--- Original Matrix (2x3) ---
[[10 20 30]
 [40 50 60]]

 --- Row Vector (1x3) ---
[1 2 3]

 --- Result of Matrix + Row Vector ---
[[11 22 33]
 [41 52 63]]

### Q85 — How do you detect and remove duplicates in pandas?

df.duplicated() returns a boolean Series. df.duplicated(subset=['col1', 'col2']) checks specific columns. df.drop_duplicates(keep='first') keeps first occurrence. keep='last' for most recent.

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {
        "Customer": ["Alice", "Bob", "Alice", "Charlie", "Bob"],
        "Item": ["Book", "Pen", "Book", "Pencil", "Pen"],
    }
)

print("--- Original DataFrame with Duplicates ---")
display(df)

# duplicated() returns a boolean Series showing which rows are exact duplicates of previous rows.
print("\n --- Which rows are duplicates? ---")
print(df.duplicated())

# drop_duplicates() returns a new DataFrame with duplicates removed.
print("\n --- After drop_duplicates() ---")
display(df.drop_duplicates())

--- Original DataFrame with Duplicates ---

  Customer    Item
0    Alice    Book
1      Bob     Pen
2    Alice    Book
3  Charlie  Pencil
4      Bob     Pen

 --- Which rows are duplicates? ---
0    False
1    False
2     True
3    False
4     True
dtype: bool

 --- After drop_duplicates() ---

  Customer    Item
0    Alice    Book
1      Bob     Pen
3  Charlie  Pencil

### Q86 — What is the difference between copy() and assignment in pandas?

df2 = df creates a reference — changes to df2 change df. df2 = df.copy() creates an independent copy. The SettingWithCopyWarning appears when pandas detects you might be modifying a copy of a slice without realising it.

In [ ]:
import pandas as pd

df = pd.DataFrame({"Score": [90, 85, 88]})

# Assignment (=) creates a REFERENCE. They point to the exact same object in memory!
df_ref = df
df_ref.loc[0, "Score"] = 100

print("--- Original DataFrame (Modified by reference!) ---")
display(df)

# .copy() creates a completely new, independent object in memory.
df_copy = df.copy()
df_copy.loc[1, "Score"] = 0

print("\n --- Original DataFrame (Unchanged by copy) ---")
display(df)

--- Original DataFrame (Modified by reference!) ---

   Score
0    100
1     85
2     88

 --- Original DataFrame (Unchanged by copy) ---

   Score
0    100
1     85
2     88

### Q87 — What does df.info() tell you?

Column names, non-null counts, dtypes, and memory usage. The most important quick-look method after loading data. Non-null count less than total rows = nulls present. Object dtype on a numeric column = data type problem.

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "Name": ["Alice", "Bob", "Charlie"],
        "Age": [25, 30, np.nan],
        "Salary": [50000.0, 60000.0, 70000.0],
        "Is_Active": [True, False, True],
    }
)

# info() is usually the first method you call on a new dataset.
# It gives a concise summary of the DataFrame:
# 1. Number of rows and columns
# 2. Column names and their data types (dtypes)
# 3. Number of non-null (missing) values per column
# 4. Memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       3 non-null      object
 1   Age        2 non-null      float64
 2   Salary     3 non-null      float64
 3   Is_Active  3 non-null      bool
dtypes: bool(1), float64(2), object(1)
memory usage: 207.0+ bytes

### Q88 — How do you pivot data in pandas?

df.pivot_table(values='revenue', index='region', columns='quarter', aggfunc='sum', fill_value=0) — cross-tabulation with aggregation. For raw pivoting without aggregation: df.pivot(index='date', columns='product', values='revenue') — fails if there are duplicate index/column pairs.

In [ ]:
import pandas as pd

# Think of pivot tables exactly like Excel Pivot Tables.
# They allow you to summarize and reshape data by aggregating values.

data = {
    "Date": ["Jan", "Jan", "Feb", "Feb", "Jan", "Feb"],
    "City": ["NY", "LA", "NY", "LA", "NY", "LA"],
    "Sales": [100, 200, 150, 250, 50, 100],
}

df = pd.DataFrame(data)

print("--- Raw Sales Data ---")
display(df)

# Let's pivot: Cities as rows, Dates as columns, and sum the Sales.
pivot = pd.pivot_table(df, values="Sales", index="City", columns="Date", aggfunc="sum")

print("\n --- Pivot Table Summary ---")
display(pivot)

--- Raw Sales Data ---

  Date City  Sales
0  Jan   NY    100
1  Jan   LA    200
2  Feb   NY    150
3  Feb   LA    250
4  Jan   NY     50
5  Feb   LA    100

 --- Pivot Table Summary ---

Date  Feb  Jan
City
LA    350  200
NY    150  150

## 🔵 Advanced Python — Q89 to Q100

> 🎯 These separate mid-level from senior. Expect these at FAANG and senior-level roles.

### Q89 — What is a metaclass?

A class whose instances are classes. By default, all classes are instances of type. A metaclass controls how classes are created. class Meta(type): ... then class MyClass(metaclass=Meta): ... Rare in application code — common in frameworks.

In [90]:
class SingletonMeta(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super().__call__(*args, **kwargs)
        return cls._instances[cls]


class Database(metaclass=SingletonMeta):
    pass


db1 = Database()
db2 = Database()
print("Same instance?", db1 is db2)

Same instance? True

### Q90 — What is __slots__ and when is it worth using?

Replaces per-instance __dict__ with a fixed descriptor. Reduces memory per instance — significant when creating millions of objects. Trade-off: you lose the ability to add arbitrary attributes. Use when memory is constrained and you know all attributes upfront.

In [89]:
import sys


class StandardObj:
    def __init__(self, a, b):
        self.a = a
        self.b = b


class SlottedObj:
    __slots__ = ["a", "b"]

    def __init__(self, a, b):
        self.a = a
        self.b = b


print("Standard dict size:", sys.getsizeof(StandardObj(1, 2).__dict__))
# print(sys.getsizeof(SlottedObj(1, 2).__dict__)) # Fails: no __dict__ exists!

Standard dict size: 296

### Q91 — What is the difference between threading and multiprocessing?

threading: multiple threads, one process, shared memory, GIL prevents true CPU parallelism. Good for I/O-bound tasks. multiprocessing: multiple processes, separate memory, true CPU parallelism. Good for CPU-bound tasks. Inter-process communication is more complex.

In [88]:
import multiprocessing


def worker(num):
    print(f"Worker {num} is running in its own process.")


if __name__ == "__main__":
    # Due to notebook environments, multiprocessing might require specific handling.
    # This is standard script syntax:
    p = multiprocessing.Process(target=worker, args=(1,))
    p.start()
    p.join()

### Q92 — What is async / await in Python?

Coroutines for asynchronous programming. async def defines a coroutine. await suspends it until the awaited operation completes — releasing control for other coroutines. Uses a single thread. Good for I/O-bound work (APIs, DBs) with high concurrency. Requires an event loop: asyncio.run(main()).

In [87]:
import asyncio


async def fetch_data():
    print("Start fetching")
    await asyncio.sleep(0.1)  # Simulate I/O
    print("Done fetching")
    return {"data": 42}


async def main():
    result = await fetch_data()
    print("Result:", result)


# Note: In Jupyter, the event loop is already running, so you can just use 'await main()'
await main()

Start fetching
Done fetching
Result: {'data': 42}

### Q93 — What is a descriptor?

An object that defines `__get__`, `__set__`, and/or `__delete__`. When accessed through a class or instance, Python calls these methods instead of returning the object directly. @property is a descriptor. Used to build `@property`, `@classmethod`, `@staticmethod`.

In [ ]:
class PositiveNumber:
    def __init__(self, name):
        self.name = name

    def __get__(self, instance, owner):
        return instance.__dict__[self.name]

    def __set__(self, instance, value):
        if value < 0:
            raise ValueError("Must be positive")
        instance.__dict__[self.name] = value


class Account:
    balance = PositiveNumber("balance")


acc = Account()
acc.balance = 100
print(acc.balance)
# acc.balance = -50  # Raises ValueError

### Q94 — What is __call__?

Makes an object callable like a function. When you do obj(), Python calls obj.__call__(). Useful for objects that need to maintain state between calls while still being callable.

In [ ]:
class Multiplier:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, x):
        return x * self.factor


double = Multiplier(2)
print("Using __call__ to multiply:", double(5))

### Q95 — What is the difference between pickle and json?

json is text-based, human-readable, language-agnostic, but only handles basic Python types. pickle is binary, Python-specific, handles almost any Python object but is a security risk when loading untrusted data (it can execute arbitrary code).

In [ ]:
import json
import pickle

data = {"name": "Alice", "roles": ["admin", "user"]}

# JSON (Text, Language-Agnostic)
json_str = json.dumps(data)
print("JSON:", json_str)

# Pickle (Binary, Python-Specific, handles arbitrary objects)
pickle_bytes = pickle.dumps(data)
print("Pickle:", pickle_bytes[:20], "...")

### Q96 — How does Python's __new__ work vs __init__?

__new__ creates the object (allocates memory). __init__ initialises it. You almost never override __new__ except for implementing singletons, immutable subclasses, or metaclass patterns. __init__ doesn't create — it sets up.

In [ ]:
class Example:
    def __new__(cls, *args, **kwargs):
        print("1. __new__ creates the instance")
        instance = super().__new__(cls)
        return instance

    def __init__(self):
        print("2. __init__ initializes it")


obj = Example()

### Q97 — What is a singleton and how do you implement it?

A class that can only have one instance. Implement via __new__:


Every call to Config() returns the same object.

In [ ]:
class Config:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

### Q98 — What is lru_cache and when do you use it?

functools.lru_cache(maxsize=128) caches function results. When called with the same arguments again, returns the cached result instantly. Use for expensive pure functions — recursive Fibonacci, API calls, database lookups with repeated inputs. Only works on functions with hashable arguments.

In [ ]:
from functools import lru_cache
import time


@lru_cache(maxsize=128)
def slow_square(n):
    time.sleep(0.5)  # Simulate expensive computation
    return n * n


start = time.time()
print(slow_square(10))
print("First call time:", time.time() - start)

start = time.time()
print(slow_square(10))  # Cached result
print("Second call time:", time.time() - start)

### Q99 — What is the difference between __iter__ and __next__?

__iter__ returns the iterator object (often self). __next__ returns the next value and raises StopIteration when done. A class implementing both is an iterator. A class implementing only __iter__ (returning a separate iterator) is an iterable.

In [ ]:
class Counter:
    def __init__(self, low, high):
        self.current = low
        self.high = high

    def __iter__(self):
        return self

    def __next__(self):
        if self.current > self.high:
            raise StopIteration
        else:
            self.current += 1
            return self.current - 1


for c in Counter(1, 3):
    print(c)

1
2
3

### Q100 — What is a Python Wheel (`.whl`) file?

> A **Python Wheel (`.whl`)** is a **pre-built package format** for Python. Since the package is already built, `pip` can install it directly without compiling the source code. This makes installation faster and more reliable. Whenever possible, `pip` automatically prefers wheels over source distributions.

### Key Points

* A `.whl` file is a **pre-built distribution** of a Python package.
* It installs **faster** because no compilation is required.
* The alternative is a **source distribution** (`.tar.gz`), which contains the package's source code.
* If only a source distribution is available, `pip` must **build/compile** the package before installing it.
* `pip install` **automatically prefers wheels** whenever they are available.

### Example

```bash
pip install numpy
```

* If a wheel is available, `pip` downloads the `.whl` file and installs it directly.
* Otherwise, `pip` downloads the source (`.tar.gz`), builds the package, and then installs it.

### Simple Comparison

* **Wheel (`.whl`)** → **Pre-built package** (ready to install).
* **Source (`.tar.gz`)** → **Source code package** (must be built before installation).